window.PASSION_CONFIG = Object.freeze({
  GOOGLE_CLIENT_ID: "",
  SPREADSHEET_ID: "1bu5qvqOIV9c3VA10Af3UPizXEzJTGmVlsZFTVvUSV0c",
  LEGACY_SHEET: "LEGACY_RAW",
  CURRENT_SHEET: "RAW_CURRENT",
  PAGE_SIZE: 50,
});
