window.PASSION_CONFIG = Object.freeze({
  GOOGLE_CLIENT_ID: "390817772097-ctj3ck53006cpmsriktv7f4jaeth92ip.apps.googleusercontent.com",
  GOOGLE_HOSTED_DOMAIN: "rcpet.edu.tw",
  SPREADSHEET_ID: "1bu5qvqOIV9c3VA10Af3UPizXEzJTGmVlsZFTVvUSV0c",
  LEGACY_SHEET: "LEGACY_RAW",
  CURRENT_SHEET: "RAW_CURRENT",
  TEACHING_SPREADSHEET_ID: "1vVSIzUr03mnjWYgZp92jNKwAhhksi38VpuRMAOUED40",
  TEACHING_FACTS_SHEET: "TEACHING_FACTS",
  TEACHING_SCHOOLS_SHEET: "DIM_SCHOOLS",
  TEACHING_DETAIL_SPREADSHEET_ID: "1N1WUYdUSUk5Tv5q_onoLADCssjdE2wDnsmaJMKiBvsE",
  TEACHING_DETAIL_SHEET: "PASSION Teaching Verified Detail Store",
  PAGE_SIZE: 50,
});
